cargo-features = ["per-package-target"]

[package]
edition = "2021"
forced-target = "./targets/riscv64gc-unknown-none-elf.json"
name = "xv6-kernel"
version = "0.1.0"

[dependencies]
buddy_system_allocator = "0.9.0"
