[package]
edition = "2021"
name = "xv6-ulib"
version = "0.1.0"

[dependencies]
xv6-panic = { path = "../xv6-panic" }

buddy_system_allocator = "0.9.0"

[lib]
crate-type = ["staticlib"]

[profile.release]
lto = true
